# Generated by Django 4.0.6 on 2022-08-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shiny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=12)),
                ('sprite', models.URLField()),
                ('date_caught', models.DateField()),
            ],
        ),
    ]
