# Generated by Django 4.0.6 on 2022-08-09 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shinydb', '0002_rename_name_shiny_nickname_remove_shiny_sprite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiny',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
