# Generated by Django 4.0.6 on 2022-08-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinydb', '0004_alter_shiny_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiny',
            old_name='owner',
            new_name='author',
        ),
    ]
